/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.myevents.vistas;

import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import mx.itson.myevents.servicios.ArrayOfEvento;

/**
 *
 * @author Admin
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarEventos();
    }

    private void cargarEventos() {
        //this.pnl_eventos
        int y = 10;
        int x_labels = 170;
        for (mx.itson.myevents.servicios.Evento evento : eventos().getEvento()) {
            Image image = null;
            try {
                URL url = new URL("http://myevents.idealabgym.com/images/upload/x150/" + evento.getImagen());
                image = ImageIO.read(url);
            } catch (IOException e) {
                e.printStackTrace();
            }
            JLabel img_evento = new JLabel(new ImageIcon(image));
            img_evento.setBounds(10, y, 150, 150);

            JLabel lbl_evento_nombre = new JLabel(evento.getNombre());
            lbl_evento_nombre.setFont(new java.awt.Font("Tahoma", 0, 18));
            lbl_evento_nombre.setBounds(x_labels, y, 355, 20);

            JLabel lbl_evento_fecha = new JLabel(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(evento.getFechaHora().toGregorianCalendar().getTime()));
            lbl_evento_fecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            lbl_evento_fecha.setBounds(x_labels, y + 30, 355, 20);

            JLabel lbl_evento_lugar_nombre = new JLabel(evento.getLugar().getNombre());
            lbl_evento_lugar_nombre.setBounds(x_labels, y + 50, 355, 20);

            JLabel lbl_evento_lugar_direccion = new JLabel(evento.getLugar().getDireccion());
            lbl_evento_lugar_direccion.setBounds(x_labels, y + 80, 355, 20);

            JLabel lbl_evento_lugar_ciudad_estado = new JLabel(evento.getLugar().getCiudad() + ", " + evento.getLugar().getEstado());
            lbl_evento_lugar_ciudad_estado.setBounds(x_labels, y + 100, 355, 20);

            JButton btn_detalles = new javax.swing.JButton();
            btn_detalles.setBackground(new java.awt.Color(0, 153, 204));
            btn_detalles.setForeground(new java.awt.Color(255, 255, 255));
            btn_detalles.setText("Detalles");
            btn_detalles.setFocusPainted(false);
            btn_detalles.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    JOptionPane.showMessageDialog(rootPane, evento.getId());
                }
            });
            btn_detalles.setBounds(420, y+125, 80, 25);
            
            JSeparator separator = new javax.swing.JSeparator();
            separator.setBounds(10, y + 160, 520, 5);

            this.pnl_eventos.add(img_evento);
            this.pnl_eventos.add(separator);
            this.pnl_eventos.add(lbl_evento_nombre);
            this.pnl_eventos.add(lbl_evento_fecha);
            this.pnl_eventos.add(lbl_evento_lugar_nombre);
            this.pnl_eventos.add(lbl_evento_lugar_direccion);
            this.pnl_eventos.add(lbl_evento_lugar_ciudad_estado);
            this.pnl_eventos.add(btn_detalles);

            y += 170;
        }
        this.pnl_eventos.setPreferredSize(new Dimension(540, y + 50));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnl_eventos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Events | Eventos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mis Datos"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Eventos"));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnl_eventos.setAutoscrolls(true);
        pnl_eventos.setFocusCycleRoot(true);

        javax.swing.GroupLayout pnl_eventosLayout = new javax.swing.GroupLayout(pnl_eventos);
        pnl_eventos.setLayout(pnl_eventosLayout);
        pnl_eventosLayout.setHorizontalGroup(
            pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        pnl_eventosLayout.setVerticalGroup(
            pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnl_eventos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
         try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         if ("Nimbus".equals(info.getName())) {
         javax.swing.UIManager.setLookAndFeel(info.getClassName());
         break;
         }
         }
         } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>

         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_eventos;
    // End of variables declaration//GEN-END:variables

    private static ArrayOfEvento eventos() {
        mx.itson.myevents.servicios.HomeService service = new mx.itson.myevents.servicios.HomeService();
        mx.itson.myevents.servicios.HomeServiceSoap port = service.getHomeServiceSoap();
        return port.eventos();
    }
}
